services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: yii2_app
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: yii2_inventory
      DB_USER: yii2_user
      DB_PASSWORD: yii2_password
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: yii2_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.6
    container_name: yii2_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: yii2_inventory
      MYSQL_USER: yii2_user
      MYSQL_PASSWORD: yii2_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  db_data:
